"""end time and question imgs

Revision ID: 0c86ce372e5c
Revises: 4f6aa9a8a911
Create Date: 2026-01-16 18:02:36.867474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c86ce372e5c'
down_revision: Union[str, Sequence[str], None] = '4f6aa9a8a911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
