"""Add new tables: ExamSession, UserCourseAccess, UserExamAccess, ResultAnnouncement, ExamSchedule, Payment

Revision ID: 59aa2f508469
Revises: 5707f8406ed9
Create Date: 2026-01-21 01:24:40.602694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59aa2f508469'
down_revision: Union[str, Sequence[str], None] = '5707f8406ed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserCourseAccess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(), nullable=False),
    sa.Column('amount_paid', sa.DECIMAL(), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['Course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_UserCourseAccess_id'), 'UserCourseAccess', ['id'], unique=False)
    op.create_table('ExamSchedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('publish_at', sa.DateTime(), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('auto_remove_at', sa.DateTime(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('is_expired', sa.Boolean(), nullable=True),
    sa.Column('is_removed', sa.Boolean(), nullable=True),
    sa.Column('send_reminder', sa.Boolean(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['Exam.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ExamSchedule_id'), 'ExamSchedule', ['id'], unique=False)
    op.create_table('ExamSession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('must_complete_by', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_submitted', sa.Boolean(), nullable=True),
    sa.Column('is_auto_submitted', sa.Boolean(), nullable=True),
    sa.Column('is_abandoned', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['Exam.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ExamSession_id'), 'ExamSession', ['id'], unique=False)
    op.create_table('Payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=False),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', name='payment_status_enum', create_constraint=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('purchase_type', sa.Enum('COURSE', 'EXAM', name='purchase_type_enum', create_constraint=True), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('gateway_response', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['Course.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['Exam.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_Payment_id'), 'Payment', ['id'], unique=False)
    op.create_table('ResultAnnouncement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('announced_at', sa.DateTime(), nullable=False),
    sa.Column('total_students', sa.Integer(), nullable=False),
    sa.Column('highest_marks', sa.DECIMAL(), nullable=True),
    sa.Column('average_marks', sa.DECIMAL(), nullable=True),
    sa.Column('result_file_url', sa.Text(), nullable=True),
    sa.Column('announced_by', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['announced_by'], ['User.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['Exam.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ResultAnnouncement_id'), 'ResultAnnouncement', ['id'], unique=False)
    op.create_table('UserExamAccess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(), nullable=False),
    sa.Column('amount_paid', sa.DECIMAL(), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['Exam.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_UserExamAccess_id'), 'UserExamAccess', ['id'], unique=False)
    op.add_column('Course', sa.Column('is_free', sa.Boolean(), nullable=True))
    op.add_column('Course', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('Course', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('Exam', sa.Column('price', sa.DECIMAL(), nullable=True))
    op.add_column('Exam', sa.Column('is_free', sa.Boolean(), nullable=True))
    op.add_column('Exam', sa.Column('result_announcement_time', sa.DateTime(), nullable=True))
    op.add_column('Exam', sa.Column('auto_remove_after_days', sa.Integer(), nullable=True))
    op.add_column('Exam', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('Exam', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('Result', sa.Column('position', sa.Integer(), nullable=True))
    op.add_column('Result', sa.Column('is_announced', sa.Boolean(), nullable=True))
    op.add_column('Result', sa.Column('announced_at', sa.DateTime(), nullable=True))
    op.add_column('Result', sa.Column('course_id', sa.Integer(), nullable=True))
    op.add_column('Result', sa.Column('session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Result', 'Course', ['course_id'], ['id'])
    op.create_foreign_key(None, 'Result', 'ExamSession', ['session_id'], ['id'])
    op.add_column('User', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('User', sa.Column('is_banned', sa.Boolean(), nullable=True))
    op.add_column('User', sa.Column('banned_at', sa.DateTime(), nullable=True))
    op.add_column('User', sa.Column('banned_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'banned_reason')
    op.drop_column('User', 'banned_at')
    op.drop_column('User', 'is_banned')
    op.drop_column('User', 'is_active')
    op.drop_constraint(None, 'Result', type_='foreignkey')
    op.drop_constraint(None, 'Result', type_='foreignkey')
    op.drop_column('Result', 'session_id')
    op.drop_column('Result', 'course_id')
    op.drop_column('Result', 'announced_at')
    op.drop_column('Result', 'is_announced')
    op.drop_column('Result', 'position')
    op.drop_column('Exam', 'is_deleted')
    op.drop_column('Exam', 'deleted_at')
    op.drop_column('Exam', 'auto_remove_after_days')
    op.drop_column('Exam', 'result_announcement_time')
    op.drop_column('Exam', 'is_free')
    op.drop_column('Exam', 'price')
    op.drop_column('Course', 'is_deleted')
    op.drop_column('Course', 'deleted_at')
    op.drop_column('Course', 'is_free')
    op.drop_index(op.f('ix_UserExamAccess_id'), table_name='UserExamAccess')
    op.drop_table('UserExamAccess')
    op.drop_index(op.f('ix_ResultAnnouncement_id'), table_name='ResultAnnouncement')
    op.drop_table('ResultAnnouncement')
    op.drop_index(op.f('ix_Payment_id'), table_name='Payment')
    op.drop_table('Payment')
    op.drop_index(op.f('ix_ExamSession_id'), table_name='ExamSession')
    op.drop_table('ExamSession')
    op.drop_index(op.f('ix_ExamSchedule_id'), table_name='ExamSchedule')
    op.drop_table('ExamSchedule')
    op.drop_index(op.f('ix_UserCourseAccess_id'), table_name='UserCourseAccess')
    op.drop_table('UserCourseAccess')
    # ### end Alembic commands ###
