"""final schema with admission request and fixes

Revision ID: 4f6aa9a8a911
Revises: 9117e4b3bbb2
Create Date: 2026-01-16 18:01:34.750529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f6aa9a8a911'
down_revision: Union[str, Sequence[str], None] = '9117e4b3bbb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AdmissionRequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['Course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_AdmissionRequest_id'), 'AdmissionRequest', ['id'], unique=False)
    op.alter_column('Answer', 'mark',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(),
               existing_nullable=True)
    op.add_column('Exam', sa.Column('end_time', sa.Date(), nullable=False))
    op.add_column('Question', sa.Column('image', sa.Text(), nullable=True))
    op.add_column('Question', sa.Column('option_a_img', sa.Text(), nullable=True))
    op.add_column('Question', sa.Column('option_b_img', sa.Text(), nullable=True))
    op.add_column('Question', sa.Column('option_c_img', sa.Text(), nullable=True))
    op.add_column('Question', sa.Column('option_d_img', sa.Text(), nullable=True))
    op.alter_column('User', 'active_mobile',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('User', 'role',
               existing_type=postgresql.ENUM('USER', 'MODERATOR', 'ADMIN', name='user_role_enum'),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'USER'::user_role_enum"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'role',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('USER', 'MODERATOR', 'ADMIN', name='user_role_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'USER'::user_role_enum"))
    op.alter_column('User', 'active_mobile',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('Question', 'option_d_img')
    op.drop_column('Question', 'option_c_img')
    op.drop_column('Question', 'option_b_img')
    op.drop_column('Question', 'option_a_img')
    op.drop_column('Question', 'image')
    op.drop_column('Exam', 'end_time')
    op.alter_column('Answer', 'mark',
               existing_type=sa.DECIMAL(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_index(op.f('ix_AdmissionRequest_id'), table_name='AdmissionRequest')
    op.drop_table('AdmissionRequest')
    # ### end Alembic commands ###
