"""user course rel fix

Revision ID: a502383a02db
Revises: b0177e125250
Create Date: 2026-01-09 20:10:12.468550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a502383a02db'
down_revision: Union[str, Sequence[str], None] = 'b0177e125250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_course', sa.Column('User_id', sa.Integer(), nullable=False))
    op.add_column('user_course', sa.Column('Course_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('user_course_course_id_fkey'), 'user_course', type_='foreignkey')
    op.drop_constraint(op.f('user_course_user_id_fkey'), 'user_course', type_='foreignkey')
    op.create_foreign_key(None, 'user_course', 'User', ['User_id'], ['id'])
    op.create_foreign_key(None, 'user_course', 'Course', ['Course_id'], ['id'])
    op.drop_column('user_course', 'course_id')
    op.drop_column('user_course', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_course', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user_course', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_course', type_='foreignkey')
    op.drop_constraint(None, 'user_course', type_='foreignkey')
    op.create_foreign_key(op.f('user_course_user_id_fkey'), 'user_course', 'User', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_course_course_id_fkey'), 'user_course', 'Course', ['course_id'], ['id'])
    op.drop_column('user_course', 'Course_id')
    op.drop_column('user_course', 'User_id')
    # ### end Alembic commands ###
