"""add_image_fields_to_question_and_exam_fields

Revision ID: 85abfd4b631f
Revises: fd24e2a34f18
Create Date: 2026-01-17 01:43:43.624854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85abfd4b631f'
down_revision: Union[str, Sequence[str], None] = 'fd24e2a34f18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Question', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('Question', sa.Column('option_a_image_url', sa.String(length=500), nullable=True))
    op.add_column('Question', sa.Column('option_b_image_url', sa.String(length=500), nullable=True))
    op.add_column('Question', sa.Column('option_c_image_url', sa.String(length=500), nullable=True))
    op.add_column('Question', sa.Column('option_d_image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Question', 'option_d_image_url')
    op.drop_column('Question', 'option_c_image_url')
    op.drop_column('Question', 'option_b_image_url')
    op.drop_column('Question', 'option_a_image_url')
    op.drop_column('Question', 'image_url')
    # ### end Alembic commands ###
