"""add_description_field_to_question

Revision ID: 001f14abe452
Revises: 85abfd4b631f
Create Date: 2026-01-17 02:34:41.946671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001f14abe452'
down_revision: Union[str, Sequence[str], None] = '85abfd4b631f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Question', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Question', 'description')
    # ### end Alembic commands ###
