"""user table updated

Revision ID: 1fb7000fe552
Revises: b845148f22d0
Create Date: 2026-01-12 17:24:27.203878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fb7000fe552'
down_revision: Union[str, Sequence[str], None] = 'b845148f22d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('active_mobile', sa.String(length=255), nullable=False))
    op.add_column('User', sa.Column('whatsapp', sa.String(length=255), nullable=False))
    op.add_column('User', sa.Column('role', app.models.enums.role.UserRole(), nullable=False))
    op.drop_column('User', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('User', 'role')
    op.drop_column('User', 'whatsapp')
    op.drop_column('User', 'active_mobile')
    # ### end Alembic commands ###
