"""Initial schema with fixed enums

Revision ID: 0fa23bea9f4b
Revises: 
Create Date: 2026-01-15 02:41:24.803314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fa23bea9f4b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create ENUM types explicitly
    user_role_enum = postgresql.ENUM(
        'USER', 'MODERATOR', 'ADMIN',
        name='user_role_enum',
        create_type=True
    )
    
    exam_type_enum = postgresql.ENUM(
        'COURSE', 'BCS_BATCH', 'BANK_BATCH', 'STANDALONE',
        name='exam_type_enum',
        create_type=True
    )
    
    question_type_enum = postgresql.ENUM(
        'MCQ', 'CQ',
        name='question_type_enum',
        create_type=True
    )
    
    # Create the enum types in the database if they don't exist
    bind = op.get_bind()
    
    def type_exists(name):
        res = bind.execute(sa.text(f"SELECT 1 FROM pg_type WHERE typname = '{name}'"))
        return res.scalar() is not None

    if not type_exists('user_role_enum'):
        user_role_enum.create(bind)
    if not type_exists('exam_type_enum'):
        exam_type_enum.create(bind)
    if not type_exists('question_type_enum'):
        question_type_enum.create(bind)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Course',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.Text(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('thumbnail', sa.Text(), nullable=False),
        sa.Column('price', sa.DECIMAL(), nullable=False),
        sa.Column('early_bird_price', sa.DECIMAL(), nullable=False),
        sa.Column('early_bird_end_date', sa.Date(), nullable=False),
        sa.Column('discount', sa.DECIMAL(), nullable=False),
        sa.Column('discount_start_date', sa.Date(), nullable=False),
        sa.Column('discount_end_date', sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Course_id'), 'Course', ['id'], unique=False)
    
    op.create_table('User',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('active_mobile', sa.String(length=20), nullable=False),
        sa.Column('whatsapp', sa.String(length=20), nullable=True),
        sa.Column('dob', sa.Date(), nullable=True),
        sa.Column('last_login', sa.Date(), nullable=True),
        sa.Column('role', postgresql.ENUM(name='user_role_enum', create_type=False), nullable=False, server_default='USER'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_id'), 'User', ['id'], unique=False)
    
    op.create_table('Exam',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('start_time', sa.Date(), nullable=False),
        sa.Column('duration_minutes', sa.Integer(), nullable=False),
        sa.Column('mark', sa.DECIMAL(), nullable=False),
        sa.Column('minus_mark', sa.DECIMAL(), nullable=False),
        sa.Column('course_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['course_id'], ['Course.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Exam_id'), 'Exam', ['id'], unique=False)
    
    op.create_table('user_course',
        sa.Column('User_id', sa.Integer(), nullable=False),
        sa.Column('Course_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['Course_id'], ['Course.id'], ),
        sa.ForeignKeyConstraint(['User_id'], ['User.id'], ),
        sa.PrimaryKeyConstraint('User_id', 'Course_id')
    )
    
    op.create_table('Question',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('q_type', sa.String(length=255), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('option_a', sa.Text(), nullable=True),
        sa.Column('option_b', sa.Text(), nullable=True),
        sa.Column('option_c', sa.Text(), nullable=True),
        sa.Column('option_d', sa.Text(), nullable=True),
        sa.Column('answer_idx', sa.Integer(), nullable=True),
        sa.Column('answer', sa.String(length=1), nullable=True),
        sa.Column('exam_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['exam_id'], ['Exam.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Question_id'), 'Question', ['id'], unique=False)
    
    op.create_table('Result',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('correct_answers', sa.Integer(), nullable=False),
        sa.Column('incorrect_answers', sa.Integer(), nullable=False),
        sa.Column('mark', sa.DECIMAL(), nullable=False),
        sa.Column('publish_time', sa.Date(), nullable=False),
        sa.Column('exam_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['exam_id'], ['Exam.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Result_id'), 'Result', ['id'], unique=False)
    
    op.create_table('Answer',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('question_id', sa.Integer(), nullable=True),
        sa.Column('exam_id', sa.Integer(), nullable=True),
        sa.Column('result_id', sa.Integer(), nullable=True),
        sa.Column('answer', sa.Integer(), nullable=True),
        sa.Column('is_correct', sa.Boolean(), nullable=True),
        sa.Column('mark', sa.Integer(), nullable=True),
        sa.Column('written_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(['exam_id'], ['Exam.id'], ),
        sa.ForeignKeyConstraint(['question_id'], ['Question.id'], ),
        sa.ForeignKeyConstraint(['result_id'], ['Result.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Answer_id'), 'Answer', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Answer_id'), table_name='Answer')
    op.drop_table('Answer')
    op.drop_index(op.f('ix_Result_id'), table_name='Result')
    op.drop_table('Result')
    op.drop_index(op.f('ix_Question_id'), table_name='Question')
    op.drop_table('Question')
    op.drop_table('user_course')
    op.drop_index(op.f('ix_Exam_id'), table_name='Exam')
    op.drop_table('Exam')
    op.drop_index(op.f('ix_User_id'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    op.drop_index(op.f('ix_Course_id'), table_name='Course')
    op.drop_table('Course')
    
    # Drop the ENUM types
    postgresql.ENUM(name='user_role_enum').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='exam_type_enum').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='question_type_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###