"""course and question model updated

Revision ID: b845148f22d0
Revises: a502383a02db
Create Date: 2026-01-12 17:15:46.459800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b845148f22d0'
down_revision: Union[str, Sequence[str], None] = 'a502383a02db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Course', sa.Column('price', sa.DECIMAL(), nullable=False))
    op.add_column('Course', sa.Column('early_bird_price', sa.DECIMAL(), nullable=False))
    op.add_column('Course', sa.Column('early_bird_end_date', sa.Date(), nullable=False))
    op.add_column('Course', sa.Column('discount', sa.DECIMAL(), nullable=False))
    op.add_column('Course', sa.Column('discount_start_date', sa.Date(), nullable=False))
    op.add_column('Course', sa.Column('discount_end_date', sa.Date(), nullable=False))
    op.add_column('Question', sa.Column('option_a', sa.Text(), nullable=True))
    op.add_column('Question', sa.Column('option_b', sa.Text(), nullable=True))
    op.add_column('Question', sa.Column('option_c', sa.Text(), nullable=True))
    op.add_column('Question', sa.Column('option_d', sa.Text(), nullable=True))
    op.add_column('Question', sa.Column('answer', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Question', 'answer')
    op.drop_column('Question', 'option_d')
    op.drop_column('Question', 'option_c')
    op.drop_column('Question', 'option_b')
    op.drop_column('Question', 'option_a')
    op.drop_column('Course', 'discount_end_date')
    op.drop_column('Course', 'discount_start_date')
    op.drop_column('Course', 'discount')
    op.drop_column('Course', 'early_bird_end_date')
    op.drop_column('Course', 'early_bird_price')
    op.drop_column('Course', 'price')
    # ### end Alembic commands ###
