"""removed options field on q

Revision ID: 0de22bc86e0b
Revises: 2026_01_25_0000
Create Date: 2026-01-26 00:17:25.777095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0de22bc86e0b'
down_revision: Union[str, Sequence[str], None] = '2026_01_25_0000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Question', 'answer_idx')
    op.drop_column('Question', 'options')
    op.alter_column('User', 'is_anonymous',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'is_anonymous',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('Question', sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('Question', sa.Column('answer_idx', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
